REM Temporarily add Git Bash bin to PATH
set "PATH=C:\Program Files\Git\usr\bin;%PATH%"

REM Verify that sed and find are accessible
where sed
where find

pause
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/01EE.txt\"|//#include \"../Data/file/01EE.txt\"#define \$SAPMLE_NAME crash1-choke/crash1-choke-RoomFar|g" {} +
pause

find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/6447.txt\"|//#include \"../Data/file/6447.txt\"#define \$SAPMLE_NAME crash2-edge/crash2-edge-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/0EFB.txt\"|//#include \"../Data/file/0EFB.txt\"#define \$SAPMLE_NAME ride1-bell/ride1-bell-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/13ZX.txt\"|//#include \"../Data/file/13ZX.txt\"#define \$SAPMLE_NAME ride1-bell/ride1-bell-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/15SA.txt\"|//#include \"../Data/file/15SA.txt\"#define \$SAPMLE_NAME crash1-choke/crash1-choke-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/1IJA.txt\"|//#include \"../Data/file/1IJA.txt\"#define \$SAPMLE_NAME snare2-head/snare2-head-DirectTop1|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/1J07.txt\"|//#include \"../Data/file/1J07.txt\"#define \$SAPMLE_NAME snare1-head/snare1-head-DirectBottom|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/1RIN.txt\"|//#include \"../Data/file/1RIN.txt\"#define \$SAPMLE_NAME crash1-bell/crash1-bell-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/1V3V.txt\"|//#include \"../Data/file/1V3V.txt\"#define \$SAPMLE_NAME crash2-edge/crash2-edge-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/1XK0.txt\"|//#include \"../Data/file/1XK0.txt\"#define \$SAPMLE_NAME ride1-bell/ride1-bell-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/24XE.txt\"|//#include \"../Data/file/24XE.txt\"#define \$SAPMLE_NAME hihat1-close/hihat1-close-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/288O.txt\"|//#include \"../Data/file/288O.txt\"#define \$SAPMLE_NAME hihat1-tight/hihat1-tight-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/2K57.txt\"|//#include \"../Data/file/2K57.txt\"#define \$SAPMLE_NAME snare1-head/snare1-head-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/2LZ3.txt\"|//#include \"../Data/file/2LZ3.txt\"#define \$SAPMLE_NAME hihat1-tight/hihat1-tight-DirectNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/2U9N.txt\"|//#include \"../Data/file/2U9N.txt\"#define \$SAPMLE_NAME ride1-bell/ride1-bell-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/38X2.txt\"|//#include \"../Data/file/38X2.txt\"#define \$SAPMLE_NAME tom5-head/tom5-head-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/3DLM.txt\"|//#include \"../Data/file/3DLM.txt\"#define \$SAPMLE_NAME hihat1-pedal/hihat1-pedal-DirectNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/3S62.txt\"|//#include \"../Data/file/3S62.txt\"#define \$SAPMLE_NAME snare2-head/snare2-head-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/3XMK.txt\"|//#include \"../Data/file/3XMK.txt\"#define \$SAPMLE_NAME tom4-head/tom4-head-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/4FLL.txt\"|//#include \"../Data/file/4FLL.txt\"#define \$SAPMLE_NAME splash2-edge/splash2-edge-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/4JC8.txt\"|//#include \"../Data/file/4JC8.txt\"#define \$SAPMLE_NAME crash2-edge/crash2-edge-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/5ASI.txt\"|//#include \"../Data/file/5ASI.txt\"#define \$SAPMLE_NAME crash1-edge/crash1-edge-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/5J01.txt\"|//#include \"../Data/file/5J01.txt\"#define \$SAPMLE_NAME tom4-head/tom4-head-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/611K.txt\"|//#include \"../Data/file/611K.txt\"#define \$SAPMLE_NAME crash1-edge/crash1-edge-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/643V.txt\"|//#include \"../Data/file/643V.txt\"#define \$SAPMLE_NAME crash1-bell/crash1-bell-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/6LWM.txt\"|//#include \"../Data/file/6LWM.txt\"#define \$SAPMLE_NAME hihat1-half/hihat1-half-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/6MBZ.txt\"|//#include \"../Data/file/6MBZ.txt\"#define \$SAPMLE_NAME china1-edge/china1-edge-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/6SJT.txt\"|//#include \"../Data/file/6SJT.txt\"#define \$SAPMLE_NAME splash2-edge/splash2-edge-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/6TJD.txt\"|//#include \"../Data/file/6TJD.txt\"#define \$SAPMLE_NAME snare2-head/snare2-head-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/7CQ8.txt\"|//#include \"../Data/file/7CQ8.txt\"#define \$SAPMLE_NAME crash2-choke/crash2-choke-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/7G28.txt\"|//#include \"../Data/file/7G28.txt\"#define \$SAPMLE_NAME hihat1-close/hihat1-close-DirectNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/7Y84.txt\"|//#include \"../Data/file/7Y84.txt\"#define \$SAPMLE_NAME hihat1-pedal/hihat1-pedal-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/8C04.txt\"|//#include \"../Data/file/8C04.txt\"#define \$SAPMLE_NAME hihat1-close/hihat1-close-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/8HC4.txt\"|//#include \"../Data/file/8HC4.txt\"#define \$SAPMLE_NAME snare1-sidestick/snare1-sidestick-DirectTop2|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/8T96.txt\"|//#include \"../Data/file/8T96.txt\"#define \$SAPMLE_NAME splash1-edge/splash1-edge-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/94NX.txt\"|//#include \"../Data/file/94NX.txt\"#define \$SAPMLE_NAME hihat1-pedal/hihat1-pedal-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/94P3.txt\"|//#include \"../Data/file/94P3.txt\"#define \$SAPMLE_NAME snare1-sidestick/snare1-sidestick-DirectTop1|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/9AG1.txt\"|//#include \"../Data/file/9AG1.txt\"#define \$SAPMLE_NAME tom3-head/tom3-head-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/9DK7.txt\"|//#include \"../Data/file/9DK7.txt\"#define \$SAPMLE_NAME tom4-head/tom4-head-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/A5YV.txt\"|//#include \"../Data/file/A5YV.txt\"#define \$SAPMLE_NAME ride1-bell/ride1-bell-DirectNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/A8UW.txt\"|//#include \"../Data/file/A8UW.txt\"#define \$SAPMLE_NAME tom3-head/tom3-head-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/B46E.txt\"|//#include \"../Data/file/B46E.txt\"#define \$SAPMLE_NAME snare2-head/snare2-head-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/B8XI.txt\"|//#include \"../Data/file/B8XI.txt\"#define \$SAPMLE_NAME china1-edge/china1-edge-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/B9CD.txt\"|//#include \"../Data/file/B9CD.txt\"#define \$SAPMLE_NAME china2-edge/china2-edge-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/BEDF.txt\"|//#include \"../Data/file/BEDF.txt\"#define \$SAPMLE_NAME hihat1-half/hihat1-half-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/BZJ9.txt\"|//#include \"../Data/file/BZJ9.txt\"#define \$SAPMLE_NAME ride1-bow/ride1-bow-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/C75T.txt\"|//#include \"../Data/file/C75T.txt\"#define \$SAPMLE_NAME tom2-head/tom2-head-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/CP1T.txt\"|//#include \"../Data/file/CP1T.txt\"#define \$SAPMLE_NAME hihat1-open/hihat1-open-DirectNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/CU9Q.txt\"|//#include \"../Data/file/CU9Q.txt\"#define \$SAPMLE_NAME hihat1-open/hihat1-open-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/CWG6.txt\"|//#include \"../Data/file/CWG6.txt\"#define \$SAPMLE_NAME hihat1-close/hihat1-close-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/D764.txt\"|//#include \"../Data/file/D764.txt\"#define \$SAPMLE_NAME splash2-edge/splash2-edge-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/D7SZ.txt\"|//#include \"../Data/file/D7SZ.txt\"#define \$SAPMLE_NAME hihat1-open/hihat1-open-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/DCIU.txt\"|//#include \"../Data/file/DCIU.txt\"#define \$SAPMLE_NAME hihat1-close/hihat1-close-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/DJ89.txt\"|//#include \"../Data/file/DJ89.txt\"#define \$SAPMLE_NAME ride1-bell/ride1-bell-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/DJ8O.txt\"|//#include \"../Data/file/DJ8O.txt\"#define \$SAPMLE_NAME tom4-head/tom4-head-DirectNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/DR5O.txt\"|//#include \"../Data/file/DR5O.txt\"#define \$SAPMLE_NAME tom5-head/tom5-head-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/DVUI.txt\"|//#include \"../Data/file/DVUI.txt\"#define \$SAPMLE_NAME ride1-bow/ride1-bow-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/EM94.txt\"|//#include \"../Data/file/EM94.txt\"#define \$SAPMLE_NAME tom5-head/tom5-head-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/FHW3.txt\"|//#include \"../Data/file/FHW3.txt\"#define \$SAPMLE_NAME kick-head/kick-head-DirectSub|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/FQT9.txt\"|//#include \"../Data/file/FQT9.txt\"#define \$SAPMLE_NAME hihat1-pedal/hihat1-pedal-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/G1IU.txt\"|//#include \"../Data/file/G1IU.txt\"#define \$SAPMLE_NAME splash1-edge/splash1-edge-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/G73D.txt\"|//#include \"../Data/file/G73D.txt\"#define \$SAPMLE_NAME splash1-edge/splash1-edge-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/G845.txt\"|//#include \"../Data/file/G845.txt\"#define \$SAPMLE_NAME crash2-bell/crash2-bell-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/GMS9.txt\"|//#include \"../Data/file/GMS9.txt\"#define \$SAPMLE_NAME snare1-sidestick/snare1-sidestick-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/GSIM.txt\"|//#include \"../Data/file/GSIM.txt\"#define \$SAPMLE_NAME tom1-head/tom1-head-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/GV17.txt\"|//#include \"../Data/file/GV17.txt\"#define \$SAPMLE_NAME kick1-head/kick1-head-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/H05H.txt\"|//#include \"../Data/file/H05H.txt\"#define \$SAPMLE_NAME kick1-head/kick1-head-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/H2DR.txt\"|//#include \"../Data/file/H2DR.txt\"#define \$SAPMLE_NAME crash1-edge/crash1-edge-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/HVI7.txt\"|//#include \"../Data/file/HVI7.txt\"#define \$SAPMLE_NAME hihat1-half/hihat1-half-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/IF5F.txt\"|//#include \"../Data/file/IF5F.txt\"#define \$SAPMLE_NAME tom1-head/tom1-head-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/IIOC.txt\"|//#include \"../Data/file/IIOC.txt\"#define \$SAPMLE_NAME kick1-head/kick1-head-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/IN97.txt\"|//#include \"../Data/file/IN97.txt\"#define \$SAPMLE_NAME tom2-head/tom2-head-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/IZ0F.txt\"|//#include \"../Data/file/IZ0F.txt\"#define \$SAPMLE_NAME splash1-edge/splash1-edge-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/J072.txt\"|//#include \"../Data/file/J072.txt\"#define \$SAPMLE_NAME kick1-head/kick1-head-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/J658.txt\"|//#include \"../Data/file/J658.txt\"#define \$SAPMLE_NAME snare2-head/snare2-head-DirectTop2|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/JTG6.txt\"|//#include \"../Data/file/JTG6.txt\"#define \$SAPMLE_NAME crash1-bell/crash1-bell-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/JWI3.txt\"|//#include \"../Data/file/JWI3.txt\"#define \$SAPMLE_NAME crash1-edge/crash1-edge-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/JXUJ.txt\"|//#include \"../Data/file/JXUJ.txt\"#define \$SAPMLE_NAME crash2-bell/crash2-bell-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/K58E.txt\"|//#include \"../Data/file/K58E.txt\"#define \$SAPMLE_NAME tom1-head/tom1-head-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/KDIQ.txt\"|//#include \"../Data/file/KDIQ.txt\"#define \$SAPMLE_NAME snare1-sidestick/snare1-sidestick-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/KGUU.txt\"|//#include \"../Data/file/KGUU.txt\"#define \$SAPMLE_NAME china1-edge/china1-edge-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/KH0Z.txt\"|//#include \"../Data/file/KH0Z.txt\"#define \$SAPMLE_NAME tom5-head/tom5-head-DirectNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/KI3W.txt\"|//#include \"../Data/file/KI3W.txt\"#define \$SAPMLE_NAME china1-edge/china1-edge-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/KK98.txt\"|//#include \"../Data/file/KK98.txt\"#define \$SAPMLE_NAME hihat1-tight/hihat1-tight-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/KMBD.txt\"|//#include \"../Data/file/KMBD.txt\"#define \$SAPMLE_NAME hihat1-tight/hihat1-tight-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/KXMA.txt\"|//#include \"../Data/file/KXMA.txt\"#define \$SAPMLE_NAME ride1-bow/ride1-bow-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/KZ0B.txt\"|//#include \"../Data/file/KZ0B.txt\"#define \$SAPMLE_NAME crash2-edge/crash2-edge-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/L6IJ.txt\"|//#include \"../Data/file/L6IJ.txt\"#define \$SAPMLE_NAME splash2-edge/splash2-edge-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/L80G.txt\"|//#include \"../Data/file/L80G.txt\"#define \$SAPMLE_NAME crash2-bell/crash2-bell-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/M1CZ.txt\"|//#include \"../Data/file/M1CZ.txt\"#define \$SAPMLE_NAME crash1-choke/crash1-choke-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/M646.txt\"|//#include \"../Data/file/M646.txt\"#define \$SAPMLE_NAME crash2-choke/crash2-choke-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/M8OD.txt\"|//#include \"../Data/file/M8OD.txt\"#define \$SAPMLE_NAME crash2-bell/crash2-bell-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/MBS0.txt\"|//#include \"../Data/file/MBS0.txt\"#define \$SAPMLE_NAME hihat1-half/hihat1-half-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/MF9F.txt\"|//#include \"../Data/file/MF9F.txt\"#define \$SAPMLE_NAME crash1-choke/crash1-choke-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/MKLJ.txt\"|//#include \"../Data/file/MKLJ.txt\"#define \$SAPMLE_NAME tom4-head/tom4-head-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/N9U8.txt\"|//#include \"../Data/file/N9U8.txt\"#define \$SAPMLE_NAME china2-edge/china2-edge-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/NDOX.txt\"|//#include \"../Data/file/NDOX.txt\"#define \$SAPMLE_NAME snare1-head/snare1-head-DirectTop1|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/NHRO.txt\"|//#include \"../Data/file/NHRO.txt\"#define \$SAPMLE_NAME tom2-head/tom2-head-DirectNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/NU49.txt\"|//#include \"../Data/file/NU49.txt\"#define \$SAPMLE_NAME hihat1-open/hihat1-open-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/NU9V.txt\"|//#include \"../Data/file/NU9V.txt\"#define \$SAPMLE_NAME tom1-head/tom1-head-DirectNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/NVQM.txt\"|//#include \"../Data/file/NVQM.txt\"#define \$SAPMLE_NAME tom3-head/tom3-head-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/O1YY.txt\"|//#include \"../Data/file/O1YY.txt\"#define \$SAPMLE_NAME tom2-head/tom2-head-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/O6HG.txt\"|//#include \"../Data/file/O6HG.txt\"#define \$SAPMLE_NAME hihat1-close/hihat1-close-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/ORWL.txt\"|//#include \"../Data/file/ORWL.txt\"#define \$SAPMLE_NAME tom3-head/tom3-head-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/OSS0.txt\"|//#include \"../Data/file/OSS0.txt\"#define \$SAPMLE_NAME snare1-head/snare1-head-DirectTop2|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/PDJ1.txt\"|//#include \"../Data/file/PDJ1.txt\"#define \$SAPMLE_NAME snare2-head/snare2-head-DirectBottom|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/PSJF.txt\"|//#include \"../Data/file/PSJF.txt\"#define \$SAPMLE_NAME snare1-head/snare1-head-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/Q16J.txt\"|//#include \"../Data/file/Q16J.txt\"#define \$SAPMLE_NAME crash1-edge/crash1-edge-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/Q6D0.txt\"|//#include \"../Data/file/Q6D0.txt\"#define \$SAPMLE_NAME crash2-bell/crash2-bell-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/QBTA.txt\"|//#include \"../Data/file/QBTA.txt\"#define \$SAPMLE_NAME hihat1-open/hihat1-open-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/QH8G.txt\"|//#include \"../Data/file/QH8G.txt\"#define \$SAPMLE_NAME crash1-bell/crash1-bell-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/QQM6.txt\"|//#include \"../Data/file/QQM6.txt\"#define \$SAPMLE_NAME ride1-bow/ride1-bow-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/QYZ9.txt\"|//#include \"../Data/file/QYZ9.txt\"#define \$SAPMLE_NAME snare2-head/snare2-head-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/RABW.txt\"|//#include \"../Data/file/RABW.txt\"#define \$SAPMLE_NAME tom5-head/tom5-head-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/RHM3.txt\"|//#include \"../Data/file/RHM3.txt\"#define \$SAPMLE_NAME china2-edge/china2-edge-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/SJ0B.txt\"|//#include \"../Data/file/SJ0B.txt\"#define \$SAPMLE_NAME crash2-edge/crash2-edge-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/T3M1.txt\"|//#include \"../Data/file/T3M1.txt\"#define \$SAPMLE_NAME hihat1-tight/hihat1-tight-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/T46Q.txt\"|//#include \"../Data/file/T46Q.txt\"#define \$SAPMLE_NAME hihat1-half/hihat1-half-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/T83I.txt\"|//#include \"../Data/file/T83I.txt\"#define \$SAPMLE_NAME snare1-head/snare1-head-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/T8E0.txt\"|//#include \"../Data/file/T8E0.txt\"#define \$SAPMLE_NAME snare1-sidestick/snare1-sidestick-DirectBottom|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/TCLW.txt\"|//#include \"../Data/file/TCLW.txt\"#define \$SAPMLE_NAME hihat1-pedal/hihat1-pedal-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/TEQT.txt\"|//#include \"../Data/file/TEQT.txt\"#define \$SAPMLE_NAME kick-head/kick-head-DirectInside|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/TQQF.txt\"|//#include \"../Data/file/TQQF.txt\"#define \$SAPMLE_NAME crash2-choke/crash2-choke-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/UD4F.txt\"|//#include \"../Data/file/UD4F.txt\"#define \$SAPMLE_NAME snare1-head/snare1-head-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/UFYV.txt\"|//#include \"../Data/file/UFYV.txt\"#define \$SAPMLE_NAME hihat1-open/hihat1-open-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/UJ0J.txt\"|//#include \"../Data/file/UJ0J.txt\"#define \$SAPMLE_NAME hihat1-pedal/hihat1-pedal-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/VGN2.txt\"|//#include \"../Data/file/VGN2.txt\"#define \$SAPMLE_NAME ride1-bow/ride1-bow-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/VJPM.txt\"|//#include \"../Data/file/VJPM.txt\"#define \$SAPMLE_NAME snare1-sidestick/snare1-sidestick-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/VWGH.txt\"|//#include \"../Data/file/VWGH.txt\"#define \$SAPMLE_NAME hihat1-tight/hihat1-tight-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/W526.txt\"|//#include \"../Data/file/W526.txt\"#define \$SAPMLE_NAME hihat1-half/hihat1-half-DirectNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/WMAG.txt\"|//#include \"../Data/file/WMAG.txt\"#define \$SAPMLE_NAME crash2-choke/crash2-choke-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/XF0Y.txt\"|//#include \"../Data/file/XF0Y.txt\"#define \$SAPMLE_NAME china2-edge/china2-edge-OverheadWide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/XXB3.txt\"|//#include \"../Data/file/XXB3.txt\"#define \$SAPMLE_NAME china2-edge/china2-edge-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/Y5TO.txt\"|//#include \"../Data/file/Y5TO.txt\"#define \$SAPMLE_NAME snare1-sidestick/snare1-sidestick-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/Y68V.txt\"|//#include \"../Data/file/Y68V.txt\"#define \$SAPMLE_NAME tom2-head/tom2-head-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/Y6RL.txt\"|//#include \"../Data/file/Y6RL.txt\"#define \$SAPMLE_NAME splash2-edge/splash2-edge-RoomFar|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/Y9XF.txt\"|//#include \"../Data/file/Y9XF.txt\"#define \$SAPMLE_NAME china1-edge/china1-edge-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/YPHP.txt\"|//#include \"../Data/file/YPHP.txt\"#define \$SAPMLE_NAME splash1-edge/splash1-edge-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/YVO4.txt\"|//#include \"../Data/file/YVO4.txt\"#define \$SAPMLE_NAME crash2-choke/crash2-choke-OverheadNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/ZAHP.txt\"|//#include \"../Data/file/ZAHP.txt\"#define \$SAPMLE_NAME ride1-bow/ride1-bow-DirectNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/ZHKM.txt\"|//#include \"../Data/file/ZHKM.txt\"#define \$SAPMLE_NAME crash1-choke/crash1-choke-OverheadMidSide|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/ZNU9.txt\"|//#include \"../Data/file/ZNU9.txt\"#define \$SAPMLE_NAME tom3-head/tom3-head-DirectNormal|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/ZRZJ.txt\"|//#include \"../Data/file/ZRZJ.txt\"#define \$SAPMLE_NAME tom1-head/tom1-head-RoomClose|g" {} +
find . -type f -name "*.txt" -exec sed -i "s|#include \"../Data/file/ZXEH.txt\"|//#include \"../Data/file/ZXEH.txt\"#define \$SAPMLE_NAME china1-edge/china1-edge-RoomClose|g" {} +

pause